### ISSUE TITLE
Add option to ignore missing or wrong "_from" in the target package.json of the target module

### ISSUE THREAD

**Issue by torkildr** [gristlabs/npm-check-shrinkwrap#1]
Currently, if the "_from" property in the package.json of the target module is missing, or wrong, this produces a "should be" message.

wrong value:
> ✗ karma-phantomjs-launcher: 1.0.2 (https://registry.npmjs.org/karma-phantomjs-launcher/-/karma-phantomjs-launcher-1.0.3.tgz) should be 1.0.2 (https://registry.npmjs.org/karma-phantomjs-launcher/-/karma-phantomjs-launcher-1.0.2.tgz)

missing value:
> ✗ karma-phantomjs-launcher: 1.0.2 should be 1.0.2 (https://registry.npmjs.org/karma-phantomjs-launcher/-/karma-phantomjs-launcher-1.0.2.tgz)

It would be nice to have an option to disable this behavior, eg. "--no-from", or similar, where any match between version in the shrinkwrap-file and the target package.json is seen as a valid match.

**Comment by dsagal** [comment]
I merged and pushed the new version to npm. Please check that to make sure this issue can be closed. Thank you!!

**Comment by torkildr** [comment]
Looks good!
